# .github/workflows/ci-prod.yml
name: CI/CD for Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      # Uncomment the following step if you want to include tests
      # - name: Run tests
      #   run: npm test

      - name: Deploy to Vercel
        env:
          NODE_ENV: production
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # Optional
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }} # Optional
        run: yarn vercel --prod --token $VERCEL_TOKEN
